query ReportData($reportCode: String!) {
  reportData {
    report(code: $reportCode) {
      title
      startTime
      fights(killType: Kills) {
        encounterID
        id
        kill
        startTime
        endTime
      }
    }
  }
}
